#!/bin/bash
# Chạy uicache sau khi cài để app hiện trên home screen
if [ -x /usr/bin/uicache ]; then
    uicache -a
elif [ -x /var/jb/usr/bin/uicache ]; then
    /var/jb/usr/bin/uicache -a
fi
# Respring nhẹ để tweak load
if [ -x /var/jb/usr/bin/sbreload ]; then
    /var/jb/usr/bin/sbreload
fi
exit 0
